### PR TITLE
Updating header styles for custom header on all pages

### PR DESCRIPTION
**Pull request by laurelfulford**
Riffing on @ryelle's PR #414.

I just updated the header styles to make sure it doesn't end up being too short on subpages. Also simplified the header classes a bit - the theme was adding both `.has-header-image` and `.no-header-image` classes, and for the most part the latter was used with `:not(.no-header-image)` so I removed it. 

See #413.

### CODE REVIEW

**Comment by melchoyce** [comment]
Looks good to me!

**Comment by laurelfulford** [comment]
This should also fix #453.

**Comment by davidakennedy** [comment]
@laurelfulford Can you refresh PR and update the default header text color?

**Comment by laurelfulford** [comment]
Redid PR as #481.

**Pull request closed without merging**
