### PR TITLE
Adjust spacing around social menu based on feedback

### PR DESCRIPTION
**Pull request by laurelfulford**
Adjust the space around the social menu, so it's even on the top and bottom.

Also bump down the site info a bit, so it lines up vertically.

### CODE REVIEW

**Comment by melchoyce** [comment]
I think this may have introduced some weirdness at smaller screen sizes: 

**Phone**
screen shot 2016-10-17 at 4 00 48 pm

**Tablet**
screen shot 2016-10-17 at 4 00 53 pm

**Around 960px**
screen shot 2016-10-17 at 4 01 01 pm

**Comment by laurelfulford** [comment]
Yeesh, I was too concerned with the top and bottom, I didn't look closely at the left and right.

Thanks for catching this, @melchoyce! Should be better spaced, now.

**Comment by melchoyce** [comment]
Soooo close! Found one more bug:

screen shot 2016-10-17 at 6 27 18 pm

**Comment by laurelfulford** [comment]
Replacing this with #447 - I made a bit of a mess with the commits.

**Pull request closed without merging**
