### PR TITLE
Remove example code for Custom Header. Fixes #28

### LINKED ISSUE #28: Remove code example from custom-header.php
The code example is not need within a finished theme: https://github.com/WordPress/twentyseventeen/commit/69482880b4ae2ec145f60df417423665581a5653#L8-L12

### PR DESCRIPTION
**Pull request by ghost**
Since it is labeled with `pr needed` :)

### CODE REVIEW

**Comment by davidakennedy** [comment]
@implenton I'd like to merge this – thanks for doing it! Can you refresh the PR?

**Comment by grappler** [comment]
This is how you can refresh the PR.
- Please update your master branch from this master branch. Doc: https://help.github.com/articles/syncing-a-fork
- Run `git checkout issue-28` then `git reset --hard master` to delete your changes and update your branch with the latest changes.
- Reapply your changes and commit them
- Then run `git push --force` to override the commits on GitHub.

**Comment by ghost** [comment]
Thanks @grappler for providing step by step instructions.

@davidakennedy I refreshed the PR.

**Comment by davidakennedy** [comment]
Thanks @implenton!

**Pull request merged**
