### PR TITLE
Uses new get_theme_file_uri functions

### LINKED ISSUE #176: Utilise get_theme_file_uri()
In WordPress 4.7, the new [`get_theme_file_uri()` function](https://make.wordpress.org/core/2016/09/09/new-functions-hooks-and-behaviour-for-theme-developers-in-wordpress-4-7/) is being introduced. This greatly improves the child theming process.

Unless TwentySeventeen is going to be backwards compatibile with WordPress < 4.7, this function should be used when enqueuing CSS and JS files from the theme.

### PR DESCRIPTION
**Pull request by joshcummingsdesign**
Uses new get_theme_file_uri(), get_parent_theme_file_uri(), and get_parent_theme_file_path() functions, closes #176

### CODE REVIEW

**Comment by grappler** [comment]
I would not do a `if else` but just do

``` php
/**
 * Twenty Seventeen only works in WordPress 4.7 or later.
 */
if ( version_compare( $GLOBALS['wp_version'], '4.7-alpha', '<' ) ) {
    require get_template_directory() . '/inc/back-compat.php';
}
```

The else is not needed as the code should stop if the `back-compat.php` is called. In `back-compat.php` I would add a new line after the `add_action` so there is a space between the functions.

**Comment by joshcummingsdesign** [comment]
@grappler Without the else statement, PHP throws an error on older versions of WordPress because it will still try to call `get_theme_file_uri()`. Adjusted the spacing.

**Comment by grappler** [comment]
@joshcummingsdesign Then we can use `return` to stop the following code to continue. So

``` php
/**
 * Twenty Seventeen only works in WordPress 4.7 or later.
 */
if ( version_compare( $GLOBALS['wp_version'], '4.7-alpha', '<' ) ) {
    require get_template_directory() . '/inc/back-compat.php';
    return;
}
```

If we are only supporting from 4.7 onwards then we can remove the function `twentyseventeen_the_custom_logo`

**Comment by davidakennedy** [comment]
Excellent work @joshcummingsdesign! Thanks for the feedback @grappler!

Closing in favor of #376.

**Comment by grappler** [comment]
@davidakennedy There is no need to create a new PR see https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by joshcummingsdesign** [comment]
Added return to remove else statement in functions.php. Removed twentyseventeen_the_custom_logo() in favor of the_custom_logo().

**Pull request closed without merging**
