### PR TITLE
<q> tag css

### LINKED ISSUE #202: q tag is unstyled
The theme test data contains a sentence that states that the `<q>` tag should put quotes around the text, but the theme stylesheet removes the quotes that are the browser default. You can see this in the screenshot of Firebug.
qtag

### PR DESCRIPTION
**Pull request by enodekciw**
Fixes #202 
Adds quotes around the text (in case it's wrapped in `<q></q>`)

### CODE REVIEW

**Comment by melchoyce** [comment]
Hey @enodekciw, how would you feel about swapping out the straight quotes `" "` for curly quotes? `“ ”` (See: http://practicaltypography.com/straight-and-curly-quotes.html)

**Comment by enodekciw** [comment]
@melchoyce swapped straight quotes for curly quotes. 
Had a merge conflict while rebasing but I think it should be good now.

**Comment by melchoyce** [comment]
I think something got messed up in your PR — I'm seeing:

`quotes: "“" "”";`

Also, looks like that styling is also applied to blockquotes. Can you remove any adjustments to `blockquote` from your PR? This styling should only effect `<q>`. Thanks!

**Comment by enodekciw** [comment]
Oh, God, I'm sorry - forgot to stage the changes before pushing them :(

Anyway, nothing's wrong with `quotes: "“" "”";` :) It is supposed to be like that. Now I've added single curly quotes for nested `<q>` tags, so it's `quotes: "“" "”" "‘" "’";` now (see: [https://css-tricks.com/almanac/properties/q/quotes/]). And no, these styles are not applied to `blockquote`.

**Comment by laurelfulford** [comment]
Thanks @enodekciw!

**Pull request merged**
