### PR TITLE
RSS widget style

### PR DESCRIPTION
**Pull request by enodekciw**
my take on #166 

@enodekciw on WordPress.org

### CODE REVIEW

**Comment by josephfusco** [comment]
Thanks for the PR! This looks good.

Instead of having both `margin-top` and `margin-bottom` on `.rss-date`, can you just add `margin-bottom` to the date and `margin-bottom` to `.rsswidget` please? This keeps it consistent with the rest of the project only using bottom margins for type.

**Review by josephfusco — APPROVED** [review]

**Comment by enodekciw** [comment]
- Rebased on top of the master branch
- Removed top margin from .rss-date
- Added 0.5em bottom margin to .rsswidget

**Comment by josephfusco** [comment]
@enodekciw This looks good now. Thank you for contributing!

**Comment by enodekciw** [comment]
Ok, I actually think it's still not ready to merge.

Just noticed that `.rsswidget` now looks ugly on hover if title spans over two or more lines (since I had to add `display: inline-block;` to make `margin-bottom` work on `.rsswidget`). Here's an example:

uglyrsswidget

Should I revert it back to how it was before? Imo, `display: inline;` looks way better on `.rsswidget` but that leaves us with `margin-top` on `.rss-date`. Opinions?

**Comment by melchoyce** [comment]
Hold on here for now — I'm going to mock up the RSS specifically to better match static front-page posts.

**Comment by melchoyce** [comment]
Added a mockup here: https://github.com/WordPress/twentyseventeen/issues/166#issuecomment-253705526

**Comment by enodekciw** [comment]
Completely rewrote the CSS for RSS widget. Now it looks like this:
rssv2
Live preview: http://2017.dekciw.lt/

**Comment by josephfusco** [comment]
@enodekciw 

Maybe it's just me but I feel like `.rssSummary` should be `margin-bottom: 0.5em` rather than the current `margin-bottom: 0.375em`. 

cc @melchoyce

**Comment by melchoyce** [comment]
Yeah, let's do `.5em` on `.rssSummary` and also do `margin: 0.5em 0 1.5em 0;` on `.widget_rss .rss-date`.

Thanks @enodekciw!

**Comment by enodekciw** [comment]
Should be all good now? :)

**Comment by melchoyce** [comment]
Looks good to me 👍 

I'll make another issue to address the RSS icon, which we might be able to replace/restyle post-SVG-merge.

**Pull request merged**
