### PR TITLE
Adding h1 to front page's content panel to improve accessibility

### PR DESCRIPTION
**Pull request by laurelfulford**
Adding h1 to front page's content panel to improve accessibility - takes care the issue with the headers.

See #288.

### CODE REVIEW

**Review by ryelle — APPROVED** [review]

**Comment by ryelle** [comment]
Actually reconsidering "ready to merge" (sorry) -- Is there a reason why the `h1` shouldn't be on the site title on the front page, even when it's panels? I understand doing it for interior pages, since the page title is more important contextually, but on the front page I would think the site title should be first-level info.

**Comment by davidakennedy** [comment]
@ryelle I think you're right here. I was thinking in terms of a normal page, but in context of panels, and `front-page.php` the site title is probably best as `h1`.

@laurelfulford will work on a change.

**Comment by laurelfulford** [comment]
Thanks @ryelle! The static front page should now use an `<h1>` on the site title, and an `<h2>` on the front page's actual page title.

**Comment by ryelle** [comment]
Looks good now :)

**Pull request merged**
