### PR TITLE
Add support for Urdu

### PR DESCRIPTION
**Pull request by grappler**
Adds support for Urdu

@ahmadawais Could you double check that this is right?

### CODE REVIEW

**Comment by ahmadawais** [comment]
@grappler I seldom work on translation these days, while `lang=ur` is def the right, I am not sure how `Tahoma` font will render Urdu. Noto on the other hand would be a better choice.

**Comment by grappler** [comment]
@ahmadawais This is how it looks in a Arabic https://github.com/WordPress/twentyseventeen/pull/398 The problem with Noto we would need to load it from Google Fonts.

**Comment by ahmadawais** [comment]
Sure go ahead then.  :)

**Comment by melchoyce** [comment]
Thanks @grappler!

I don't see Urdu in the Site Language list:

screen shot 2016-10-18 at 9 17 31 pm
screen shot 2016-10-18 at 9 18 01 pm

Is there anything special I need to do to find it?

**Comment by grappler** [comment]
Urdu is at 95% so that is why it is not showing up. https://translate.wordpress.org/locale/ur/default/wp/dev

**Comment by melchoyce** [comment]
Thanks 👍

**Pull request merged**
