### PR TITLE
Adding missing space from CSS. 

### PR DESCRIPTION
**Pull request by laurelfulford**
I accidentally removed a space when fixing a merge conflict in #317. This update fixes that.

### CODE REVIEW

**Comment by laurelfulford** [comment]
Re: Travis - only the PHP: 5.5 check failed, with the error:

`The command "git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR" failed and exited with 128 during .`

**Comment by laurelfulford** [comment]
Resolved the Travis issue by pushing another change - thanks for the tip, @josephfusco!

**Comment by karmatosed** [comment]
Looks like conflicts are still there for this :/

**Comment by davidakennedy** [comment]
Looks like this isn't needed any longer, closing.

**Pull request closed without merging**
