### PR TITLE
Cut animation/transition times in half

### PR DESCRIPTION
**Pull request by josephfusco**
Fixes: #240 

wp.org [joefusco](https://profiles.wordpress.org/joefusco)

### CODE REVIEW

**Comment by ntwb** [comment]
In stylelint we have a rule [time-no-imperceptible](http://stylelint.io/user-guide/rules/time-no-imperceptible/):

> _"Disallow `animation` and `transition` less than or equal to 100ms."_

The human eye supposedly can only see animation > 150ms

So, with the PR #247 @josephfusco just submitted changing many instances of `transition` to `100ms` are these transitions actually noticeable at all from applying that PR?

Instead of `100ms` / `0.1s` should these be 150ms? Or removed all together?

cc @melchoyce

**Comment by josephfusco** [comment]
@ntwb makes sense.

The fixed navigation sliding out is being removed with #151, but in the places where the color and background color is inverted on hover like the dropdowns and current link styles, IMO it is still noticeable.

**Comment by ntwb** [comment]
Related/Duplicate: #252

**Comment by josephfusco** [comment]
Closing this as #240 discussion is going to change the :hover behavior all together rather than just cutting duration times down.

**Pull request closed without merging**
