### PR TITLE
Add clearfix for blockquote

### LINKED ISSUE #210: Blockquote looks awkward with image floated left.
screen shot 2016-10-08 at 12 48 03 pm

Same issue came up in Twenty Sixteen: https://github.com/WordPress/twentysixteen/issues/462
Twenty Sixteen solution: https://github.com/WordPress/twentysixteen/pull/463

### PR DESCRIPTION
**Pull request by josephfusco**
Fixes #210 

wp.org username: [joefusco](https://profiles.wordpress.org/joefusco)

### CODE REVIEW

**Comment by melchoyce** [comment]
Hey @josephfusco, I'm not seeing a difference between the before and after when I apply this PR. Can you take a screenshot of what it should look like?

**Comment by josephfusco** [comment]
Sure thing!

## Before

screen shot 2016-10-10 at 8 58 50 pm

## After

screen shot 2016-10-10 at 8 59 15 pm

**Comment by melchoyce** [comment]
Weird. Here's my before/after, on Mac 10.11.6 / Chrome 53.0.2785.143:

## Before

screen shot 2016-10-10 at 9 10 40 pm

## After

screen shot 2016-10-10 at 9 11 01 pm

**Comment by josephfusco** [comment]
@melchoyce can you paste the contents of your editor here please so I can compare?

**Comment by melchoyce** [comment]
Here you go: https://gist.github.com/melchoyce/9d58b099cdccb1834143a95ab5519adc

**Comment by josephfusco** [comment]
Thanks! Your left aligned image is inside the blockquote. It should be outside and above to see this behavior.

Try with this https://gist.github.com/josephfusco/0e172adb154a101d1d0ded2c774daf47

**Comment by melchoyce** [comment]
Ah, there we go :) 

Looks good 👍

**Pull request merged**
