### PR TITLE
FIX: Several Documentation Minor Issues as per the Standards. Fixes: #68

### LINKED ISSUE #68: Several Minor Documentation Issues
Throughout the theme, there are several minor documentation issues as per the [WP PHP Documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#6-file-headers). I plan to fix them with a PR.
- [x] FIX: There should be no period for file headers' summary 
- [x] FIX: More than two times a parameter has not been documented
- [x] FIX: Many files have no file DocBlock
- [x] NEW: @pacakge WordPress
- [x] NEW: @subpackage Twenty_Seventeen ( I'd opt for a new package name which should be a single word instead of two words.
- [x] NEW: @since (I'd opt for adding @since 1.0.0 to each and every file head)

Looking forward!

### PR DESCRIPTION
**Pull request by ahmadawais**
Throughout the theme, there are several minor documentation issues. This PR fixes them all.
- There should be no period for file headers' summary as per the [WP PHP Documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#6-file-headers).
- More than two times a parameter had not been documented which is now fixed
- Added file DocBlocks to several files.

Fixes: #68 
- [x] FIX: There should be no period for file headers' summary 
- [x] FIX: More than two times a parameter has not been documented
- [x] FIX: Many files have no file DocBlock
- [x] NEW: @pacakge WordPress
- [x] NEW: @subpackage Twenty_Seventeen ( I'd opt for a new package name which should be a single word instead of two words.
- [x] NEW: @since (I'd opt for adding @since 1.0.0 to each and every file head)

W.org Username: `mrahmadawais`

### CODE REVIEW

**Comment by ahmadawais** [comment]
@davidakennedy Would love to get your feedback on this.

P.S. Apologies for the tag in the wrong PR. I basically went ahead and consolidated two different PRs into this one.

**Review by josephfusco — APPROVED** [review]

**Comment by ahmadawais** [comment]
@josephfusco Thanks for the approval. 👍

**Comment by davidakennedy** [comment]
@ahmadawais This looks pretty good – thanks again! A few points of feedback:
- Package headers need to match other default themes. See: https://github.com/WordPress/twentysixteen/blob/master/archive.php#L14-L16
- Can you refresh this PR? It has a merge conflict now.
- If you refresh it, please add your WordPress.org username in a comment so I have it for reference.

**Comment by ahmadawais** [comment]
@davidakennedy Thanks for taking a look at this. 

> Package headers need to match other default themes. See: https://github.com/WordPress/twentysixteen/blob/master/archive.php#L14-L16

Sure, I can handle that. Would you want me to add these to all the files? I agree these headers should be there. I just didn't want to overstep too much here. 

Anywho, I think the @since tag is wrong. The correct one as stated in the standards would be 

``` php
/**
 * Summary (no period for file headers)
 *
 * Description. (use period)
 *
 * @link URL
 *
 * @package WordPress
 * @subpackage Component
 * @since x.x.x (when the file was introduced)
 */
```

So, I will add this to all the files and will add @since 1.0.0 for now. Since sections can also be used to keep a [changelog](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#since-section-changelogs), which I think is pretty important. But that has nothing to do with this PR at this point.

Let me know if that's fine by you. I mean the format for each file header. I would also like to volunteer to keep a check on each and every file of TwentySeventeen to help it conform with the standards. This will help us set the right expectations and example for new developers as well. 

Looking forward to a go-ahead from your end! 

Cheers!

**Comment by ahmadawais** [comment]
@davidakennedy PR has been refreshed. I have also resolved the conflicts. I think it would be a lot better to merge this PR before any other PR since it will run into conflicts with every other PR and will go stale. 

Looking forward!

**Comment by davidakennedy** [comment]
Thanks @ahmadawais! I just tweaked the since header slightly since default themes don't have minor releases generally. And when they do, it just bumps up to 1.1, etc.

**Comment by ahmadawais** [comment]
@davidakennedy oh! I didn't know that. I have become accustomed to using X.X.X styled version numbers as per the standards. Thanks for merging the PR. Looking forward to contribute more.

**Pull request merged**
