### PR TITLE
Update Normalize to version 5.0

### PR DESCRIPTION
**Pull request by josephfusco**
Not much changed as I think the last version used might have been taken from the latest master of https://github.com/necolas/normalize.css/ so we were already almost at 5.0.0.

wp.org username: [joefusco](https://profiles.wordpress.org/joefusco)

### CODE REVIEW

**Comment by josephfusco** [comment]
Fixes #130

**Review by ntwb — CHANGES_REQUESTED** [review]
I see lots of changes @josephfusco, here's the diff between 4.2.0 and 5.0.0:

https://github.com/necolas/normalize.css/compare/4.2.0...5.0.0

**Comment by josephfusco** [comment]
@ntwb Yes but it looks like this commit (https://github.com/WordPress/twentyseventeen/pull/92/commits/afc1707e8cf51757cdb367db21e37b9efab6c4fa) already contained a number of these changes when we upgraded to 4.2.0 which leads me to believe this commit updated from the latest master and not the 4.2.0 packaged release.

**Comment by ntwb** [comment]
> ...which leads me to believe this commit updated from the latest master and not the 4.2.0 packaged release.

Agreed 👍

**Review by ntwb — APPROVED** [review]
Looks good 👍

**Review by ahmadawais — APPROVED** [review]

**Comment by ahmadawais** [comment]
LGTM 💯

**Pull request merged**
