### PR TITLE
Add @version to php doc block

### PR DESCRIPTION
**Pull request by Zodiac1978**
See Issue #72

### CODE REVIEW

**Comment by Zodiac1978** [comment]
Updated. See #72

**Comment by davidakennedy** [comment]
@Zodiac1978 Thanks for the update! One bit of feedback, and a question:
- Can you change `1.0.0` to `1.0`? Default themes in general don't do the minor release number, so that third number isn't needed. Sorry, should have mentioned that.
- Question: It looks like you've stuck to just the main template files? Should we do this will all files? Like the partials included in `components`?

Thanks!

**Comment by Zodiac1978** [comment]
@davidakennedy I've changed the version number according to your feedback. I missed the partials totally. They are included with `get_template_part` so they can be changed via child theme, so I would want to add versions for them too.

The files in `inc` are included via `get_template_directory` so they are not meant to be overridden via child theme and the `functions.php` is not overridden but an addition - so for my intended use case it is not necessary to add version number for these files.

**Comment by davidakennedy** [comment]
@Zodiac1978 Right, that makes sense. I really only meant the partials that had template code. 😄  Thanks for the update!

**Comment by bueltge** [comment]
Small hint to the version format, like 1.0.0 vs 1.0. I think all public projects should use the semantic versioning, not a custom style. Is much easier to document, understand and also important, easier to contributing. More about semantic versioninig is [on the page](http://semver.org/) to this topic.

**Pull request merged**
