### PR TITLE
Make sure 'scroll down' arrow is actually hidden on small screens

### PR DESCRIPTION
**Pull request by laurelfulford**
The 'scroll down' arrow is no longer hidden on small screens. Looks like one selector was made more specific, but not the other.

It looked like this:

image

This PR should fix it.

### CODE REVIEW

**Comment by grappler** [comment]
There seems to be somethig wrong with this PR.

**Comment by ntwb** [comment]
It looks like the latest commit here in this PR does not want to play nice https://github.com/WordPress/twentyseventeen/pull/351/commits/11ea1d72bec2e3e9743adc2d481b70b276b7fad5

**Comment by laurelfulford** [comment]
Yikes, yeah - will delete and redo.

**Comment by laurelfulford** [comment]
Replaced by #421.

**Pull request closed without merging**
