### PR TITLE
CSS Coding Standards Fixes

### PR DESCRIPTION
**Pull request by ntwb**
This pull request address outstanding CSS Coding Standards per:
• https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/

### CODE REVIEW

**Comment by ntwb** [comment]
Following up this PR will be a refresh of vendor prefixes in #379

**Comment by josephfusco** [comment]
GitHub seems to only allow inline commenting on changes, so I will add this here.

https://github.com/WordPress/twentyseventeen/blob/6a03a3a6d6fbf58abfd3dd16c9051f1916919bc8/style.css#L323 (Linking to unrelated commit incase line number changes)

^ Comment should be on same line with property/value.

**Review by josephfusco — CHANGES_REQUESTED** [review]
GitHub seems to only allow inline commenting on changed parts of files, so I will add this here.

https://github.com/WordPress/twentyseventeen/blob/6a03a3a6d6fbf58abfd3dd16c9051f1916919bc8/style.css#L323 (Linking to unrelated commit incase line number changes)

^ Comment should be on same line with property/value.

**Comment by ntwb** [comment]
Done @josephfusco

**Review by josephfusco — APPROVED** [review]

**Comment by josephfusco** [comment]
Prematurely added ready to merge label before travis check. ;) Looks good though!

**Comment by ntwb** [comment]
> Prematurely added ready to merge label before travis check. ;) Looks good though!

Travis CI doesn't touch CSS files 😏

**Pull request merged**
