### PR TITLE
New abbreviation style for Abbr elements with a title

### PR DESCRIPTION
**Pull request by jordesign**
This is a new style that is subtler - to avoid clashing visually with all the horizontal rules we have around the place.

Before:
image

After:
image

### CODE REVIEW

**Comment by ntwb** [comment]
This PR is empty

**Comment by jordesign** [comment]
That's awkward... I'll resubmit

**Comment by jordesign** [comment]
Sorry @melchoyce looks like the change didn't actually make it in that PR - can I resubmit?

**Comment by melchoyce** [comment]
Sorry, I'm not sure how I managed to do that. Let me figure out how to revert.

**Comment by melchoyce** [comment]
Looks like I can't revert because it because nothing was changed. I think it was a by-product of #234 somehow...? Anyway, go ahead and resubmit. :)

**Comment by ntwb** [comment]
I think its from both your local @melchoyce and @jordesign local rebase/merges conflicting somehow, the `cursor: pointer;` is from #173 a day ago and the other change is from #228 also a day ago... With all that said I _think_ everything looks correct now though /shrug

**Pull request merged**
